#
# Drone pipeline to build Docker image.
#

kind: pipeline
type: docker
name: arm-test

platform:
  os: linux
  arch: arm64

steps:

- name: build-only
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE}/${DRONE_REPO_NAME##docker-}
    build_args:
    - DOCKER_IMAGE_VERSION=drone-ci
    dry_run: true
  when:
    ref:
      exclude:
      - refs/tags/v*

