name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide some details about the host running the container.
        Examples:
          - The operating system version (e.g. Ubuntu 22.04).
          - CPU architecture (amd64, arm, arm64, etc).
          - The Docker version (output of `docker version`).
          - Model of the NAS, if applicable (e.g. Synology DS418, QNAP TS-364, etc).
          - Indicate if a network share is mapped to a folder of the container.
          - Browser and OS used to access the application's UI.
          - Anything else specific to your environment.
      value: |
          - OS:
          - CPU:
          - Docker version:
          - Device model:
          - Browser/OS:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Container creation
      description: |
        How did you create the container ?
        Examples:
          - The `docker run` command used.
          - The compose file used.
          - Screenshots from the management tool (e.g. Portainer, unRAID, erc) showing container settings.
    validations:
      required: true
  - type: textarea
    id: container-log
    attributes:
      label: Container log
      description: Please copy/paste the output of `docker logs <container name>`.
      render: text
    validations:
      required: true
  - type: textarea
    id: container-inspect
    attributes:
      label: Container inspect
      description: |
        If the container is running, please provide the output of `docker inspect <container name>`.
        **Attention**: If you defined passwords, secrets or any sensitive information via environment variables, make sure to remove them from the output.
      render: text
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything that will give more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
