name: Docker Baseimage CI

env:
  DOCKER_IMAGE: jlesage/baseimage

on:
  push:
    branches: '*'
    tags: v*.*.*
  pull_request:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      fail-fast: false
      matrix:
        info:
          - '{ "tag_prefix": "alpine-3.6",        "baseimage": "alpine:3.6",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.7",        "baseimage": "alpine:3.7",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.8",        "baseimage": "alpine:3.8",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.9",        "baseimage": "alpine:3.9",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.10",       "baseimage": "alpine:3.10",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.11",       "baseimage": "alpine:3.12",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.12",       "baseimage": "alpine:3.12",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.6-glibc",  "baseimage": "alpine:3.6",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.7-glibc",  "baseimage": "alpine:3.7",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.8-glibc",  "baseimage": "alpine:3.8",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.9-glibc",  "baseimage": "alpine:3.9",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.10-glibc", "baseimage": "alpine:3.10",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.11-glibc", "baseimage": "alpine:3.11",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "alpine-3.12-glibc", "baseimage": "alpine:3.12",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "debian-8",          "baseimage": "debian:jessie-slim",  "platforms": "linux/amd64,linux/386,linux/arm/v5,linux/arm/v7" }'
          - '{ "tag_prefix": "debian-9",          "baseimage": "debian:stretch-slim", "platforms": "linux/amd64,linux/386,linux/arm/v5,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "debian-10",         "baseimage": "debian:buster-slim",  "platforms": "linux/amd64,linux/386,linux/arm/v5,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "ubuntu-16.04",      "baseimage": "ubuntu:xenial",       "platforms": "linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "ubuntu-18.04",      "baseimage": "ubuntu:bionic",       "platforms": "linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8" }'
          - '{ "tag_prefix": "ubuntu-20.04",      "baseimage": "ubuntu:focal",        "platforms": "linux/amd64,linux/arm/v7,linux/arm64/v8" }'

    steps:
      - name: Prepare
        id: prep
        run: |
          # Determine the Docker container version.
          VERSION=github-ci
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          else
            echo "::error::Unexpected GITHUB_REF: $GITHUB_REF"
            exit 1
          fi
          # Determine the version to put in container label.
          LABEL_VERSION=${VERSION}
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            LABEL_VERSION=${VERSION:1}
          fi
          # Determine the Docker container tags.
          TAGS="${{ env.DOCKER_IMAGE }}:${{ fromJSON(matrix.info).tag_prefix }}-${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${{ env.DOCKER_IMAGE }}:${{ fromJSON(matrix.info).tag_prefix }}-${MINOR}"
            TAGS="$TAGS,${{ env.DOCKER_IMAGE }}:${{ fromJSON(matrix.info).tag_prefix }}-${MAJOR}"
            TAGS="$TAGS,${{ env.DOCKER_IMAGE }}:${{ fromJSON(matrix.info).tag_prefix }}"
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${{ env.DOCKER_IMAGE }}:${{ fromJSON(matrix.info).tag_prefix }}-sha-${GITHUB_SHA::8}"
          fi
          # Determine the Dockerfile to use.
          if [[ "${{ fromJSON(matrix.info).tag_prefix }}" =~ alpine-* ]]; then
            if [[ "${{ fromJSON(matrix.info).tag_prefix }}" =~ *-glibc ]]; then
              DOCKERFILE=Dockerfile.alpine-glibc
            else
              DOCKERFILE=Dockerfile.alpine
            fi
          else
            DOCKERFILE=Dockerfile.debian
          fi
          # Export outputs.
          echo ::set-output name=dockerfile::${DOCKERFILE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=label_version::${LABEL_VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=platforms::linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup BATS
        uses: mig4/setup-bats@v1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ steps.prep.outputs.dockerfile }}
          platforms: ${{ fromJSON(matrix.info).platforms }}
          tags: localhost:5000/${{ env.DOCKER_IMAGE }}:github-ci
          build-args: |
            BASEIMAGE=${{ fromJSON(matrix.info).baseimage }}
            IMAGE_VERSION=${{ steps.prep.outputs.label_version }}

      - name: Inspect
        id: inspect
        run: |
          docker buildx imagetools inspect localhost:5000/${{ env.DOCKER_IMAGE }}:github-ci
          echo ::set-output name=raw::$(docker buildx imagetools inspect --raw localhost:5000/${{ env.DOCKER_IMAGE }}:github-ci)

      - name: Test image
        run: |
          if [ -d tests ]; then
            #for IMG in $(docker buildx imagetools inspect localhost:5000/${{ env.DOCKER_IMAGE }}:github-ci | grep "  Name:" | awk '{print $2}')
            for IMG in ${{ join(fromJSON(steps.inspect.outputs.raw).manifests.*.digest, ' ') }}
            do
              DOCKER_IMAGE=$IMG bats tests
            done
          else
            echo "::warning::No tests to execute."
          fi

#      - name: Build and push to Dockerhub
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          file: ${{ fromJSON(matrix.info).dockerfile }}
#          #cache-from: type=local,src=/tmp/.buildx-cache
#          #cache-to: type=local,dest=/tmp/.buildx-cache
#          platforms: ${{ steps.prep.outputs.platforms }}
#          tags: ${{ steps.prep.outputs.tags }}
#          build-args: |
#            BASEIMAGE=${{ fromJSON(matrix.info).baseimage }}
#            IMAGE_VERSION=${{ steps.prep.outputs.label_version }}


      - name: Push to Dockerhub
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker pull localhost:5000/${{ env.DOCKER_IMAGE }}:github-ci
          for tag in $(echo "${{ steps.prep.outputs.tags }}" | tr ',' ' '); do
            docker tag localhost:5000/${{ env.DOCKER_IMAGE }}:github-ci $tag
            docker push $tag
          done

      - name: MicroBadger webhook
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        # https://github.com/marketplace/actions/webhook-action
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.MICROBADGER_WEBHOOK_URL }}

  post-build:
    name: Post-build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub description
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        # https://github.com/marketplace/actions/docker-hub-description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE }}
          readme-filepath: DOCKERHUB.md


  notification:
    name: Notification
    needs: [ build, post-build ]
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Get workflow conclusion
        uses: technote-space/workflow-conclusion-action@v1

      - name: Pushover notification
        if: ${{ always() }}
        # https://github.com/marketplace/actions/github-action-for-pushover-notifications
        uses: desiderati/github-action-pushover@v1
        with:
          job-status: ${{ env.WORKFLOW_CONCLUSION }}
          pushover-api-token: ${{ secrets.PUSHOVER_API_TOKEN }}
          pushover-user-key: ${{ secrets.PUSHOVER_USER_KEY }}


#      - name: Checkout
#        # https://github.com/marketplace/actions/checkout
#        uses: actions/checkout@v2
#
#      - name: Build Image
#        # https://github.com/marketplace/actions/customizable-docker-buildx
#        uses: ilteoood/docker_buildx@v1
#        with:
#          imageName: ${{ steps.prepare.outputs.docker_image_name }}
#          tag: ${{ steps.prepare.outputs.docker_image_tags }}
#          buildArg: DOCKER_IMAGE_VERSION=${{ steps.prepare.output.docker_image_version }}
#          platform: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
#          publish: ${{ startsWith(github.ref, 'refs/tags/') }}
#          dockerHubUser: ${{ secrets.DOCKERHUB_USERNAME }}
#          dockerHubPassword: ${{ secrets.DOCKERHUB_PASSWORD }}

      # https://github.com/crazy-max/ghaction-docker-buildx
#      - name: Set up Docker Buildx
#        uses: crazy-max/ghaction-docker-buildx@v1
#        with:
#          version: latest

#      - name: Docker Buildx (no push)
#        run: |
#          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
#            --output "type=image,push=false" \
#            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
#            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
#            --build-arg "VERSION=${{ steps.prepare.outputs.version }}" \
#            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
#            --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
#            --file Dockerfile .

#      - name: Docker Login
#        if: success() && startsWith(github.ref, 'refs/tags/')
#        env:
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.prepare.outputs.docker_username }}" --password-stdin

#      - name: Docker Buildx (push)
#        if: success() && startsWith(github.ref, 'refs/tags/')
#        run: |
#          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
#            --output "type=image,push=true" \
#            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
#            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
#            --build-arg "VERSION=${{ steps.prepare.outputs.version }}" \
#            --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
#            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
#            --file Dockerfile .

#      - name: Docker Check Manifest
#        if: success() && startsWith(github.ref, 'refs/tags/')
#        run: |
#          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image_name }}:v${{ steps.prepare.outputs.idocker_image_version }}

#      - name: Clear
#        if: always() && startsWith(github.ref, 'refs/tags/')
#        run: |
#          rm -f ${HOME}/.docker/config.json

